# If ~/.bin exists, then add it to the PATH variable
if [ -d "$HOME/bin" ] ; then
  PATH=$PATH:$HOME/.bin
fi

if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

platform=$(uname)

# If platform is a mac
if ["$platform" = "Darwin"]
then
  alias ls='ls -1G'
# If platform is a linux machine
elif ["$platform" = "Linux"]
then
  alias ls='ls -1 --color'
fi

alias ll='ls -al'
alias ta='tmux attach -t'
alias tl='tmux list-sessions'
alias tn='tmux new -s'
alias tk='tmux kill-session -t'

## Prompt

#USERNAME=
#PS1="\h [\W]"
